### ISSUE TITLE
Make state machine definition more flexible

### ISSUE THREAD

**Issue by jibweb** [v4r-tuwien/grasping_pipeline#11]
smach enable the definition of sequences of states that behaves as states themselves. We have the definition of most states and their combination for one specific instances [here](https://github.com/v4r-tuwien/grasping_pipeline/blob/main/scripts/statemachine.py), but it would be very nice to have defined more flexibly.
Ideally, we should be able to define a state machine that does grasping and handover, and another one that does grasping and placement with minimal code duplication using [smach properties](http://wiki.ros.org/smach/Tutorials/Create%20a%20hierarchical%20state%20machine)

This is also a good opportunity to create a clearer documented number of states. What I mean is that ideally, there should not be a VeRefine state, and a PyraPose state, but rather a PoseEstimation state with a clearly defined interface, that can be implemented either by VeRefine code or PyraPose code, etc. This makes the grasping pipeline code much more adaptable, and makes it much easier to test new methods (one clear interface needs to be implented, and that's it)

**Comment by jibweb** [comment]
I would also simplify the user input aspect as part of this effort. If the different path pyrapose/verefine are handled by having different action implementation in the background that's also easier. And different state machines can simply different launch files depending on the needs?

Right now, the user input sort of defeats the purpose of a state machine, as most states can be executed any time, instead of things in the right order. The check before action execution can be replaced by a single user input in the ExecuteGraspAction 

Let me know if I am missing something important here.

NB: There is a [smach viewer](http://wiki.ros.org/smach/Tutorials/Smach%20Viewer) to help understand what is happening, and as part of tracebot, I have been working on a "tracer" that logs input and output of every action and sequence executed into a json file. It should be easy to adapt to smach, if you think that could be useful

**Comment by jibweb** [comment]
As part of this effort, we need to come up with a common message for different methods. Current proposal for the known object pipeline (the step going from object pose to grasp pose will still be defined in the grasping_pipeline):

```
#GOAL
sensor_msgs/CameraInfo cam_info
sensor_msgs/Image color_image 
sensor_msgs/Image depth_image  # should be registered to the color image
string object_to_locate  # optional , if unspecified, returns everything found
---
#RESULT
geometry_msgs/PoseStamped[] poses
float32[6] box_extents  # Extent along +x, -x, +y, -y, +z, -z as the box might not be centered on the pose origin
float32[] confidences
string[] categories  # category name or instance name
---
# FEEDBACK
```

For the method performing pose estimation separately from the detection, a reference implementation of Mask-RCNN trained on relevant objects (YCB instances + classes relevant for Robocup@home) and a plane pop-out object detection will be provided with the following action definition to call from the object pose estimation wrapper:

```
#GOAL
sensor_msgs/CameraInfo cam_info
sensor_msgs/Image color_image 
sensor_msgs/Image depth_image  # should be registered to the color image
string object_to_locate  # optional , if unspecified, returns everything found
---
#RESULT
float32[] confidences
string[] categories # category name or instance name
sensor_msgs/RegionOfInterest[] bboxes # A list of bounding boxes for all detected objects
sensor_msgs/Image image # An image that can be used to send segmentation masks (value in image correspond to index of bbox + 1, as 0 correspond to the absence of objects)
# optionally an oriented bbox? I feel like the segmentation mask and the depth images are enough to recover what might be needed?
---
# FEEDBACK
```

Another message suitable for unknown object pipeline (should be suitable for direct grasp estimation, like plane pop-out+HAF, or gpd, or dexnet):

```
#GOAL
sensor_msgs/CameraInfo cam_info
sensor_msgs/Image color_image 
sensor_msgs/Image depth_image # should be registered to the color image
---
#RESULT
geometry_msgs/PoseStamped[] grasp_poses
float32[] confidences
---
# FEEDBACK
```

For references:
*  [Here](https://gitlab.informatik.uni-bremen.de/robokudo/robokudo_msgs/-/blob/main/action/GenericImgProcAnnotator.action) is the message used in RoboKudo (Bremen vision pipeline)
* The [project diagram](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1#R5Vtbd9o4EP41nLP7kBxfMJfHBEK6vRDapGn7xBG2sJUaySuLAP31K9kS%2BErMxhBz0ofGHkm2PPN9mhlpaJmDxfqWgsD7QhzotwzNWbfMYcsw9H7f4n%2BEZCMlumXGEpciR8p2gnv0B0qhJqVL5MAw1ZER4jMUpIU2wRjaLCUDlJJVutuc%2BOm3BsCFOcG9Dfy89AdymBdLe5a2k3%2BAyPXUm3VNtiyA6iwFoQccskqIzJuWOaCEsPhqsR5AX2hP6SUeNypp3U6MQsyqDIDhYPbz6etdsHrE7vyr%2B8O8dy5M%2BZhn4C%2FlF7eMjs8feO2gZ37pissrjIESz6iSKgl%2FZaJvwfCTDI1UzDbKbisPMXgfAFvcrzg4eSePLXx%2Bp%2FPLOfL9AfEJjXqbHaBp87mQE8wS8nn0j8tDRslvmGgxu5o2GGzfnDSDUimkDK4TImmWW0gWkNEN7yJbJUckRbbQX%2B3w1lao8pJY60khkBh3t0%2FewYBfSCQcgAq9WwUVH5c%2B4rDQPi093DJHTQfIGcJSnwEdGofAUtM6N1ejemCpmylctvV%2BNVwa2tFw2amCy3sG5wBHwIS46fg4Q1R2NNDnK8QBqDSG3Q4HRS2obJvtl2GpFy2X%2Ff6RYGl0chqFDo8i5C2hzCMuwcC%2F2UmvKVliBzpSxbs%2BnwkJpPAJMraRIRFYMpK2Clwj9pNfa5fcgcS3vxJNQ6EvTd1s1A3mHxyPstTtr2Tbblh0p8aVGi4kS2rDfZyVQRugLmT7lCi9oNDcXhxQ6AOGntPxWf027b%2BtTbtnZtPuajz89vT4adx%2B6I03n8dY%2F%2FOg%2BjXEpKbxtib9HxbVm8XR2ikaDb2iFGwSHQKCMAsTT54IQcID6OmAWa32o7L%2BWjaQ0TJYimewQ9b2U14RquQilTnCztSlIAyCeH6vcsIOgL25XeRsO3YPzub1ONttKCdV1y9ITawCX9s5VgTYzqmVzJ5E3s8%2FlIRQgDNkiOfeiIgIMIT0GdlC%2FJcKhUTG4lE4j0Z3%2Fl2K9JvrmYn9hCsxOWPkIuYtZ5c2WfCb5za9YMsVEqHkKH7Z1IGM%2FyF0ughdDtTRzCcz8TkAiU4h5ZHWSM4DTsW8wmnILiO5eqOKxVyIIUW2mPgaLAIOhl3IBlSnvw8FSx1xVjvDGjMfZ%2BnGKW1v5WzvIBrbPqJVMQZOrjij1zTFqUSuCY5P2%2Bv4XuHCtIo%2BrN2omERNuyCjPdVCxV%2BB8EvL1COMuxWtTq%2F0ZPOeDe1CTzbrWcK71LOcWWlWWm%2FPyvY7YGXtGUBxiGdlQ7xsrh8vC5Nt4DWqOdor30Y%2FlMbhgwd8D4jLwd3kJk9FKT1PGlq9xtHQegc0NN4JDY3jeNNnqJwkCqAfuUHlSoNgPqU83iQURh7VjmXJa95uExdzKNApJaHyxcr7yrZivzuZjM6W6129aVw3GrQDdDSu9yoGws3ab1XTrpu6HpjHmy4Iu8kAOGSQCkbZcZY4GgDfvhX9osUpvIeUA%2F1SNWdp%2BeHqfGmZzU8bQMt3kJ8qhR7bBZvZbZsTu2CjPKEtOKk8lNqAQRwA4T3dwBHOtIDSsV%2BNM9%2BY%2BmGxb72dDItJfIQz09NQW29ckmucTZJbdoq2PYKp%2FdRlW892Xp7aKM91E3wZwvWYf9T5csloGpXM3ltSSU8SaUurF6nUPdGJtKoeOJsjzPS5mkJN6RFmpr%2Bquyrrb3bNff2Pc%2BRp5A9oPmGyEtH1d%2Fw7vtK2x3Wxg36jI5pupuTSzJ9rnpjcZpVF9QfYKGSNHhFcqRuuDb4U%2Bn6U42ic8yy9Vb%2B%2FbOwLsj0Q1W1fg6UIoU5SRQYMTYsKlypXkXVGmlZbFZmRJlSnm0eAUXSyvYVF%2FRAoL248NEy2PYpCZ43EltSSoDAf%2B36%2F%2B%2Bf%2BfDPYDH3NgorpE9O3vGD6VbsXDMx8OA18gOEUrhkF4jBPyCmEmXO83M6hGCQ0TYILviCcrbH1duOM3T%2BOsQ84s437UIKNqSxxif5CWpzpfgHh74tvg%2FH4fFHQNBC0X9jnSChUWUM4uoswCrQ5FjSukXVso4y11HNE%2F1c9SBbCR532R2AawA7%2F%2F041TeI6mptEHc2eoCCeaOVi9Sao5iME%2BOIaBAyFTHxpIrKSuhiq2qJbWVtUqpMSDRwcP3EqsDTVgI9cbr%2BhzYnDAzPzWhAG2cC%2Fkg0L5Dhxngf5RwtnITMp%2BTH8udZ1yxqKZ%2FHULlZM9Og0WzHBMENtKaqDu2Y61uoVVBFa3ZOSt3wLozKyrDLSgdATbuAbmZHBMipKoySmVWUKnQMwxIzlroFRW1yXBkrBIr%2BtQE3ipF0DTgrr1xt0LnHMnwBkNkNe3IHZV%2Btfrf7u1Pstlto8q1gynitkqLlkfJ8G928BZF00R8%2FORcXlr9Xcz0dgi7hSe1j6wA5fGQRWrkbPLQYFYCtP2jM%2F%2FTLbBQuE1q3FkYjSjO1Ps2ML737hbt78Bw%3D%3D) for the current batch of Sasha bachelor students include links to a lot of message definitions


@lexihaberl @ChristianXEder @sThalham: I would love your opinion on this !

**Comment by jibweb** [comment]
I would love some feedback, but I think it would make sense to directly follow University of Bremen expected messages:
They are defined [here](https://gitlab.informatik.uni-bremen.de/robokudo/robokudo_msgs/-/blob/main/action/GenericImgProcAnnotator.action) and [here (multi images)](https://gitlab.informatik.uni-bremen.de/robokudo/robokudo_msgs/-/blob/main/action/GenericImgListProcAnnotator.action) or just below:


```
#goal
sensor_msgs/Image rgb
sensor_msgs/Image depth
string description

---
#result
bool success
string result_feedback

# A list of bounding boxes for all detected objects
sensor_msgs/RegionOfInterest[] bounding_boxes

# Class IDs for each entry in bounding_boxes
int32[] class_ids

# Class confidence for each entry in bounding_boxes
float32[] class_confidences

# An image that can be used to send preprocessed intermediate results,
# inferred segmentation masks or maybe even a result image, depending on the use case
sensor_msgs/Image image

# The best pose for each entry in bounding_boxes
geometry_msgs/Pose[] pose_results

# Array-based string feedback when generating text for all detected objects etc.
string[] descriptions

---
#feedback
string feedback
```

**Comment by sThalham** [comment]
At some point it might be limiting that only one pose and segmentation is
returned per bbox. Thinking about part-based estimates, which is actually
likely to not be inferred at the same time. So probably no troubles there.

Generally, it appears quite versatile and thought through. I also like the
use of standard message desriptions.

**Comment by jibweb** [comment]
I think if needs be, we could also work around that limitation by having multiple copies of the same bounding box and different poses at the corresponding positions

**Comment by lexihaberl** [comment]
I think that issue is done for now.
