### ISSUE TITLE
Investigate why graspchecker sometimes gets stuck

### ISSUE THREAD

**Issue by lexihaberl** [v4r-tuwien/grasping_pipeline#16]
Sometimes the GraspChecker gets stuck in an infinite loop in the ```get_tf_transform()``` function. The reason for that is that the time stamp that is passed to ```lookup_transform()``` sometimes strongly deviates from the actual ROS time, which means that no transform can be found, because that time stamp is too far in the past. I have no idea how this can happen since the GraspChecker runs on the ROS master and should therefore have the same clock?
Once this clock-related problem starts, the FindGrasppointServer (which calls the GraspChecker) needs to be restarted to resolve this issue.

**Comment by hoenigpeter** [comment]
@dzimmer999 can be closed?

**Comment by lexihaberl** [comment]
The new version of the GraspChecker (called GraspAnnotator) doesn't use this function call anymore. It uses the TF2Wrapper now instead. So the original issue is gone.

But unfortunately we recently had a related/similar issue in the new version of the GraspChecker/GraspAnnotator. This might have been fixed with this [commit ](https://github.com/v4r-tuwien/v4r_util/commit/f5d551d84458e136fa8d3fff9da427144d427398), but I would probably wait and monitor the situation for the next ~2 weeks to see whether the problem is actually gone.
