### ISSUE TITLE
Dependencies: Container Verefine could not be build

### ISSUE THREAD

**Issue by ChristianXEder** [v4r-tuwien/grasping_pipeline#6]
I think the problem is somewhere in the maskrcnn container. I have saved the correct Python packages with pip freeze on Robbie. 

+ Container on Robbie crashes with error: "Error processing request: ‘NoneType’ object is not iterable" in ros_pose_estimation.py, line 142

**Comment by markusltnr** [comment]
I have updated https://github.com/v4r-tuwien/detectron2_ros and https://github.com/v4r-tuwien/verefine_pipeline
