### ISSUE TITLE
Position fails after handover

### ISSUE THREAD

**Issue by ChristianXEder** [v4r-tuwien/grasping_pipeline#9]
When I use the command T for cleaning the table, the robot grasp the first object and make the handover. At this point everything is alright. Then he tries to go back to the first position, but at this position the orientation is wrong. He stands with the back to the table, so 180° incorrect. Maybe it is a problem with the marker from Elisabeth, but could be a failure in the code.

**Comment by lexihaberl** [comment]
I never had this issue in the past 2 years, so I guess this issue is irrelevant for the current implementation.
